"""Run fusion-aware attacks against two late-fused unimodal classifiers.

The complete classifier attacked by this script is:

    fused_score = fusion(text_model(text), image_model(image))

The text and image perturbations are generated independently from the clean
sample. In particular:

* the text attack changes the text while keeping the clean image fixed;
* the image attack changes the image while keeping the clean text fixed;
* the both-perturbed result combines those two independently generated
  perturbations; it does not alternate or re-optimise them.

Despite this independence, both attacks optimise the fused score rather than
the output of one unimodal model. ``mean``, ``min`` and ``max`` use native
PyTorch operations. ``svm-rbf`` supports the ``StandardScaler + SVC``
pipeline generated by ``plot_multimodal_score_space.py`` and reproduces its
binary RBF decision function with differentiable PyTorch operations so that
PGD can backpropagate through the late-fusion classifier.

By default the output layout matches the existing late-fusion evaluation:

    results/.../perturbed/late-fusion/<fusion>/perturbed_results.csv
    results/.../perturbed/late-fusion/<fusion>/text-perturbed/...
    results/.../perturbed/late-fusion/<fusion>/image-perturbed/...

The first file is the independently both-perturbed scenario. Existing files
at those paths are replaced, consistently with the other attack scripts.
Every result CSV includes the fused output and the two component outputs used
by the score-space plot.

``--pgd-iters`` and ``--max-variants`` are the effective budgets used by one
invocation. A single-modality scope defaults to the full corresponding
unimodal budget; ``both`` defaults to half of each budget.
"""

from __future__ import annotations

import argparse
import glob
import json
import os
import sys
from pathlib import Path
from typing import Any

os.environ["TF_ENABLE_ONEDNN_OPTS"] = "0"
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))

import joblib
import numpy as np
import torch
from PIL import Image
from sentence_transformers import util
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from torch.utils.data import DataLoader
from tqdm import tqdm
from transformers import AutoModelForMaskedLM, AutoTokenizer

from data_loading import my_datasets
from configuration_files.configuration import (
    ALPHA_FACTOR,
    ATTACK_MODEL,
    COMMAND,
    DEVICE,
    DEVICE_MLM,
    EPSILON,
    K_BERT_ATTACK,
    LATE_FUSION_SVM_INPUT,
    MAX_CANDIDATES_PER_WORD,
    MAX_WORDS_FOR_IMPORTANCE,
    MAX_WORDS_TO_ATTACK,
    MIN_TXT_SIMILARITY,
    SOURCE_LABEL,
    SUBSET_SIZE,
    TARGET_LABEL,
    THRESHOLD_PRED_SCORE,
    late_fusion_attack_budgets,
)
from configuration_files.paths import (
    CLEAN_IMAGE_PARAMS,
    CLEAN_TEXT_PARAMS,
    LATE_FUSION_DATA_DIR,
    RESULT_PATH,
    TRAIN_SVM_MODEL,
    late_fusion_scenario_path,
)
from attacks.trepat.modifier import Modifier
from attacks.trepat.rephraser import Rephraser
from utils import (
    TargetedTrepatAttacker,
    bertattack as bertattack_attack,
    img_perturbation,
    load_available_datasets,
    load_model,
    model_sbert,
    save_perturbed_image,
    save_perturbed_texts,
    save_predictions,
    visible_text_window,
)


PARAMETER_KEYS = {
    "Name LLM",
    "Image Embedder Name",
    "Model Path",
    "Number of Tokens",
    "Merge Tokens",
    "LoRA Alpha",
    "LoRA R",
    "LoRA Dropout",
    "Use LoRA",
    "Dataset",
}

COMPONENT_OUTPUT_NAMES = (
    "text_scores",
    "text_logits",
    "image_scores",
    "image_logits",
)
COMPONENT_OUTPUT_COLUMNS = tuple(name[:-1] for name in COMPONENT_OUTPUT_NAMES)


def read_parameters(path: Path, description: str) -> dict[str, Any]:
    """Read and validate one clean-model parameter file."""
    try:
        with path.open("r", encoding="utf-8") as handle:
            parameters = json.load(handle)
    except FileNotFoundError as error:
        raise FileNotFoundError(
            f"{description} parameters do not exist: {path}. "
            "Run the clean unimodal evaluation first."
        ) from error
    except json.JSONDecodeError as error:
        raise ValueError(
            f"Invalid JSON in {description} parameters: {path}"
        ) from error

    missing = PARAMETER_KEYS.difference(parameters)
    if missing:
        raise ValueError(
            f"{description} parameters are missing: "
            f"{', '.join(sorted(missing))}"
        )

    return parameters


def parse_args() -> tuple[
    argparse.Namespace,
    dict[str, Any],
    dict[str, Any],
]:
    """Parse arguments, using the two clean parameter files as defaults."""
    parameter_parser = argparse.ArgumentParser(add_help=False)
    parameter_parser.add_argument(
        "--text-parameters",
        "--text_parameters",
        dest="text_parameters",
        type=Path,
        default=Path(CLEAN_TEXT_PARAMS),
    )
    parameter_parser.add_argument(
        "--image-parameters",
        "--image_parameters",
        dest="image_parameters",
        type=Path,
        default=Path(CLEAN_IMAGE_PARAMS),
    )
    parameter_args, _ = parameter_parser.parse_known_args()

    text_parameters = read_parameters(
        parameter_args.text_parameters,
        "Text model",
    )
    image_parameters = read_parameters(
        parameter_args.image_parameters,
        "Image model",
    )

    parser = argparse.ArgumentParser(
        parents=[parameter_parser],
        description=(
            "Attack the score produced by late-fusing separately trained text "
            "and image classifiers."
        ),
    )

    model_group = parser.add_argument_group("late-fusion classifier")
    model_group.add_argument(
        "--fusion",
        choices=("mean", "min", "max", "svm-rbf", "svm_rbf"),
        default="mean",
    )
    model_group.add_argument(
        "--text-model-path",
        "--text_model_path",
        dest="text_model_path",
        type=Path,
        default=Path(text_parameters["Model Path"]),
    )
    model_group.add_argument(
        "--image-model-path",
        "--image_model_path",
        dest="image_model_path",
        type=Path,
        default=Path(image_parameters["Model Path"]),
    )
    model_group.add_argument(
        "--svm-model",
        "--svm_model",
        dest="svm_model",
        type=Path,
        default=Path(TRAIN_SVM_MODEL),
        help="Fitted StandardScaler + probabilistic RBF-SVC pipeline.",
    )
    model_group.add_argument(
        "--svm-input",
        "--svm_input",
        dest="svm_input",
        choices=("scores", "logits"),
        default=LATE_FUSION_SVM_INPUT,
    )
    model_group.add_argument(
        "--threshold",
        type=float,
        default=0.5,
        help="Decision threshold applied to the fused score.",
    )

    data_group = parser.add_argument_group("data and output")
    data_group.add_argument(
        "--dataset",
        default=text_parameters["Dataset"],
    )
    data_group.add_argument(
        "--test-data",
        "--test_data",
        dest="test_data",
        type=Path,
        default=None,
        help=(
            "Test annotation file. "
            "By default data_loading/<dataset>/test.* is used."
        ),
    )
    data_group.add_argument(
        "--images-dir",
        "--images_dir",
        dest="images_dir",
        type=Path,
        default=None,
        help=(
            "Image directory. "
            "By default data_loading/<dataset>/images is used."
        ),
    )
    data_group.add_argument(
        "--batch-size",
        "--batch_size",
        dest="batch_size",
        type=int,
        default=int(text_parameters.get("Batch Size", 1)),
    )
    data_group.add_argument(
        "--n-tokens",
        "--n_tokens",
        dest="n_tokens",
        type=int,
        default=int(text_parameters["Number of Tokens"]),
    )
    data_group.add_argument(
        "--subset-size",
        "--subset_size",
        dest="subset_size",
        type=int,
        default=SUBSET_SIZE,
    )
    data_group.add_argument(
        "--num-workers",
        "--num_workers",
        dest="num_workers",
        type=int,
        default=0,
    )
    data_group.add_argument(
        "--results-path",
        "--results_path",
        dest="results_path",
        type=Path,
        default=Path(RESULT_PATH),
    )
    data_group.add_argument(
        "--output-dir",
        "--output_dir",
        dest="output_dir",
        type=Path,
        default=None,
        help=(
            "Output base. By default: "
            "<results-path>/perturbed/late-fusion/<fusion>."
        ),
    )
    data_group.add_argument(
        "--dump-dir",
        "--dump_dir",
        dest="dump_dir",
        type=Path,
        default=None,
        help=(
            "Qualitative sample directory. By default: "
            "data_perturbed/late-fusion/<fusion>/<scope>."
        ),
    )

    attack_group = parser.add_argument_group("attack")
    attack_group.add_argument(
        "--attack-scope",
        "--attack_scope",
        dest="attack_scope",
        choices=("text", "image", "both"),
        default="both",
        help=(
            "'both' independently attacks text and image from the clean "
            "sample and evaluates their combined result."
        ),
    )
    attack_group.add_argument(
        "--attack-method",
        "--attack_method",
        dest="attack_method",
        choices=("trepat", "bertattack"),
        default="trepat",
    )
    attack_group.add_argument(
        "--source-label",
        "--source_label",
        dest="source_label",
        type=int,
        choices=(0, 1),
        default=SOURCE_LABEL,
    )
    attack_group.add_argument(
        "--target-label",
        "--target_label",
        dest="target_label",
        type=int,
        choices=(0, 1),
        default=TARGET_LABEL,
    )
    attack_group.add_argument(
        "--pgd-iters",
        "--pgd_iters",
        dest="pgd_iters",
        type=int,
        default=None,
        help=(
            "Effective PGD iterations. Defaults to the full image budget for "
            "image-only and half for both."
        ),
    )
    attack_group.add_argument(
        "--max-variants",
        "--max_variants",
        dest="max_variants",
        type=int,
        default=None,
        help=(
            "Effective maximum TRePAT variants. Defaults to the full text "
            "budget for text-only and half for both."
        ),
    )
    attack_group.add_argument(
        "--epsilon",
        type=float,
        default=EPSILON,
    )
    attack_group.add_argument(
        "--alpha-factor",
        dest="alpha_factor",
        type=float,
        default=ALPHA_FACTOR,
    )
    attack_group.add_argument(
        "--k",
        type=int,
        default=K_BERT_ATTACK,
    )
    attack_group.add_argument(
        "--threshold-pred-score",
        dest="threshold_pred_score",
        action=argparse.BooleanOptionalAction,
        default=THRESHOLD_PRED_SCORE,
    )
    attack_group.add_argument(
        "--max-words-to-attack",
        dest="max_words_to_attack",
        type=int,
        default=MAX_WORDS_TO_ATTACK,
    )
    attack_group.add_argument(
        "--max-candidates-per-word",
        dest="max_candidates_per_word",
        type=int,
        default=MAX_CANDIDATES_PER_WORD,
    )
    attack_group.add_argument(
        "--max-words-for-importance",
        dest="max_words_for_importance",
        type=int,
        default=MAX_WORDS_FOR_IMPORTANCE,
    )
    attack_group.add_argument(
        "--min-txt-similarity",
        dest="min_txt_similarity",
        type=float,
        default=MIN_TXT_SIMILARITY,
    )

    args = parser.parse_args()

    if args.fusion == "svm_rbf":
        args.fusion = "svm-rbf"

    default_budgets = late_fusion_attack_budgets(args.attack_scope)
    if args.pgd_iters is None:
        args.pgd_iters = default_budgets["pgd_iters"]
    if args.max_variants is None:
        args.max_variants = default_budgets["max_variants"]

    return args, text_parameters, image_parameters


def validate_args(
    args: argparse.Namespace,
    text_parameters: dict[str, Any],
    image_parameters: dict[str, Any],
) -> None:
    """Validate experiment inputs before loading large models."""
    if args.source_label == args.target_label:
        raise ValueError(
            "Source and target labels must be different"
        )

    if args.target_label != 1 - args.source_label:
        raise ValueError(
            "This binary attack requires "
            "target_label == 1 - source_label"
        )

    if not 0.0 < args.threshold < 1.0:
        raise ValueError(
            "--threshold must be strictly between 0 and 1"
        )

    if args.batch_size <= 0:
        raise ValueError(
            "--batch-size must be positive"
        )

    if args.n_tokens <= 0:
        raise ValueError(
            "--n-tokens must be positive"
        )

    if (
        args.subset_size is not None
        and args.subset_size <= 0
    ):
        raise ValueError(
            "--subset-size must be positive"
        )

    if args.num_workers < 0:
        raise ValueError(
            "--num-workers cannot be negative"
        )

    if args.pgd_iters <= 0:
        raise ValueError(
            "--pgd-iters must be positive"
        )

    if args.max_variants <= 0:
        raise ValueError(
            "--max-variants must be positive"
        )

    if args.epsilon < 0:
        raise ValueError(
            "--epsilon cannot be negative"
        )

    if args.alpha_factor <= 0:
        raise ValueError(
            "--alpha-factor must be positive"
        )

    if not 0.0 <= args.min_txt_similarity <= 1.0:
        raise ValueError(
            "--min-txt-similarity must be between 0 and 1"
        )

    if not args.text_model_path.is_file():
        raise FileNotFoundError(
            f"Text-model weights do not exist: "
            f"{args.text_model_path}"
        )

    if not args.image_model_path.is_file():
        raise FileNotFoundError(
            f"Image-model weights do not exist: "
            f"{args.image_model_path}"
        )

    if (
        args.fusion == "svm-rbf"
        and not args.svm_model.is_file()
    ):
        raise FileNotFoundError(
            f"RBF-SVM model does not exist: "
            f"{args.svm_model}"
        )

    text_dataset = text_parameters["Dataset"]
    image_dataset = image_parameters["Dataset"]

    if text_dataset != image_dataset:
        raise ValueError(
            "The clean text and image models were evaluated on "
            "different datasets: "
            f"{text_dataset!r} != {image_dataset!r}"
        )

    if args.dataset != text_dataset:
        print(
            "Warning: --dataset overrides the dataset stored in "
            f"the clean parameters ({text_dataset!r})."
        )


def model_args_from_parameters(
    parameters: dict[str, Any],
    modality: str,
    model_path: Path,
) -> argparse.Namespace:
    """Build exactly the namespace expected by ``utils.load_model``."""
    return argparse.Namespace(
        modality=modality,
        name_llm=parameters["Name LLM"],
        name_img_embed=parameters["Image Embedder Name"],
        model_path=str(model_path),
        n_tokens=int(parameters["Number of Tokens"]),
        merge_tokens=parameters["Merge Tokens"],
        lora_alpha=parameters["LoRA Alpha"],
        lora_r=parameters["LoRA R"],
        lora_dropout=parameters["LoRA Dropout"],
        use_lora=parameters["Use LoRA"],
        set_params=False,
    )


class DifferentiableRBFSVMFusion(torch.nn.Module):
    """Differentiable binary StandardScaler + RBF-SVC probability model."""

    def __init__(self, fitted_model: Any):
        super().__init__()

        scaler: StandardScaler | None = None
        svc: SVC

        if isinstance(fitted_model, Pipeline):
            steps = list(fitted_model.steps)

            if (
                not steps
                or not isinstance(steps[-1][1], SVC)
            ):
                raise TypeError(
                    "The final SVM pipeline step must be "
                    "sklearn.svm.SVC"
                )

            svc = steps[-1][1]
            preprocessing = [
                step
                for _, step in steps[:-1]
                if step != "passthrough"
            ]

            if (
                len(preprocessing) > 1
                or (
                    preprocessing
                    and not isinstance(
                        preprocessing[0],
                        StandardScaler,
                    )
                )
            ):
                raise TypeError(
                    "Differentiable SVM fusion supports only an "
                    "optional StandardScaler before SVC"
                )

            if preprocessing:
                scaler = preprocessing[0]

        elif isinstance(fitted_model, SVC):
            svc = fitted_model

        else:
            raise TypeError(
                "--svm-model must contain an SVC or a "
                "Pipeline ending in SVC"
            )

        if svc.kernel != "rbf":
            raise ValueError(
                f"Expected an RBF SVC, got kernel={svc.kernel!r}"
            )

        if not getattr(svc, "probability", False):
            raise ValueError(
                "The SVC must have been trained with probability=True"
            )

        if getattr(svc, "n_features_in_", None) != 2:
            raise ValueError(
                "The SVC must use exactly [text, image] "
                "as its two features"
            )

        if (
            len(svc.classes_) != 2
            or 1 not in svc.classes_
        ):
            raise ValueError(
                "The SVC must be binary and contain class 1; "
                f"got {svc.classes_}"
            )

        if (
            len(svc.probA_) != 1
            or len(svc.probB_) != 1
        ):
            raise ValueError(
                "The fitted SVC does not contain binary "
                "probability calibration"
            )

        if scaler is None:
            mean = np.zeros(
                2,
                dtype=np.float32,
            )
            scale = np.ones(
                2,
                dtype=np.float32,
            )
        else:
            if getattr(scaler, "n_features_in_", None) != 2:
                raise ValueError(
                    "The StandardScaler must contain exactly "
                    "two features"
                )

            mean = (
                np.asarray(
                    scaler.mean_,
                    dtype=np.float32,
                )
                if scaler.with_mean
                else np.zeros(
                    2,
                    dtype=np.float32,
                )
            )
            scale = (
                np.asarray(
                    scaler.scale_,
                    dtype=np.float32,
                )
                if scaler.with_std
                else np.ones(
                    2,
                    dtype=np.float32,
                )
            )

        self.register_buffer(
            "mean",
            torch.as_tensor(mean),
        )
        self.register_buffer(
            "scale",
            torch.as_tensor(scale),
        )
        self.register_buffer(
            "support_vectors",
            torch.as_tensor(
                np.asarray(svc.support_vectors_),
                dtype=torch.float32,
            ),
        )
        self.register_buffer(
            "dual_coef",
            torch.as_tensor(
                np.asarray(svc.dual_coef_[0]),
                dtype=torch.float32,
            ),
        )
        self.register_buffer(
            "intercept",
            torch.tensor(
                float(svc.intercept_[0]),
                dtype=torch.float32,
            ),
        )
        self.register_buffer(
            "gamma",
            torch.tensor(
                float(svc._gamma),
                dtype=torch.float32,
            ),
        )
        self.register_buffer(
            "prob_a",
            torch.tensor(
                float(svc.probA_[0]),
                dtype=torch.float32,
            ),
        )
        self.register_buffer(
            "prob_b",
            torch.tensor(
                float(svc.probB_[0]),
                dtype=torch.float32,
            ),
        )

        # LibSVM's binary calibration orientation is established against the
        # fitted sklearn model once. This also handles an unusual class order.
        transformed_points = np.asarray(
            svc.support_vectors_[
                : min(
                    32,
                    len(svc.support_vectors_),
                )
            ]
        )

        if scaler is not None:
            raw_points = scaler.inverse_transform(
                transformed_points
            )
        else:
            raw_points = transformed_points

        decision = np.asarray(
            fitted_model.decision_function(raw_points)
        ).reshape(-1)

        calibrated = 1.0 / (
            1.0
            + np.exp(
                np.clip(
                    (
                        svc.probA_[0] * decision
                        + svc.probB_[0]
                    ),
                    -80,
                    80,
                )
            )
        )

        positive_column = int(
            np.flatnonzero(
                np.asarray(fitted_model.classes_) == 1
            )[0]
        )

        sklearn_probability = fitted_model.predict_proba(
            raw_points
        )[:, positive_column]

        direct_error = float(
            np.mean(
                np.abs(
                    calibrated
                    - sklearn_probability
                )
            )
        )
        inverse_error = float(
            np.mean(
                np.abs(
                    (1.0 - calibrated)
                    - sklearn_probability
                )
            )
        )

        self.invert_probability = (
            inverse_error < direct_error
        )

        approximation_error = min(
            direct_error,
            inverse_error,
        )

        if approximation_error > 0.05:
            raise ValueError(
                "The differentiable SVM probability does not "
                "match sklearn closely enough "
                f"(mean absolute error={approximation_error:.4f})"
            )

    def forward(
        self,
        features: torch.Tensor,
    ) -> torch.Tensor:
        """Return the differentiable probability of class 1."""
        features = features.to(
            dtype=self.support_vectors.dtype
        )

        transformed = (
            features - self.mean
        ) / self.scale

        squared_distance = (
            transformed.unsqueeze(1)
            - self.support_vectors.unsqueeze(0)
        ).square().sum(dim=-1)

        kernel = torch.exp(
            -self.gamma * squared_distance
        )

        decision = (
            kernel.matmul(self.dual_coef)
            + self.intercept
        )

        probability = torch.sigmoid(
            -(
                self.prob_a * decision
                + self.prob_b
            )
        )

        if self.invert_probability:
            probability = 1.0 - probability

        return probability


class LateFusionClassifier(torch.nn.Module):
    """Expose two frozen unimodal models and score fusion as one classifier."""

    def __init__(
        self,
        text_model: torch.nn.Module,
        image_model: torch.nn.Module,
        fusion: str,
        svm_fusion: DifferentiableRBFSVMFusion | None = None,
        svm_input: str = "scores",
    ):
        super().__init__()

        self.text_model = text_model
        self.image_model = image_model
        self.fusion = fusion
        self.svm_fusion = svm_fusion
        self.svm_input = svm_input

        if fusion not in {
            "mean",
            "min",
            "max",
            "svm-rbf",
        }:
            raise ValueError(
                f"Unknown fusion: {fusion}"
            )

        if (
            fusion == "svm-rbf"
            and svm_fusion is None
        ):
            raise ValueError(
                "svm_fusion is required for fusion='svm-rbf'"
            )

        if svm_input not in {
            "scores",
            "logits",
        }:
            raise ValueError(
                f"Unknown SVM input space: {svm_input}"
            )

        # Parameters stay frozen, while gradients with respect to the input
        # image remain available to PGD.
        for parameter in self.text_model.parameters():
            parameter.requires_grad_(False)

        for parameter in self.image_model.parameters():
            parameter.requires_grad_(False)

        self.text_model.eval()
        self.image_model.eval()

    @staticmethod
    def _vector(
        value: torch.Tensor,
        name: str,
    ) -> torch.Tensor:
        if not torch.is_tensor(value):
            raise TypeError(
                f"{name} must be a tensor"
            )

        if value.ndim == 0:
            value = value.unsqueeze(0)

        if (
            value.ndim > 2
            or (
                value.ndim == 2
                and value.shape[1] != 1
            )
        ):
            raise ValueError(
                f"{name} must contain one scalar per sample; "
                f"got {value.shape}"
            )

        return value.reshape(-1)

    def forward(
        self,
        images: Any,
        texts: Any,
        return_components: bool = False,
    ) -> tuple[torch.Tensor, ...]:
        if images is None or texts is None:
            raise ValueError(
                "Late fusion requires both image and text inputs"
            )

        text_score, text_logit = self.text_model(
            None,
            texts,
        )
        image_score, image_logit = self.image_model(
            images,
            None,
        )

        text_score = self._vector(
            text_score,
            "text score",
        )
        image_score = self._vector(
            image_score,
            "image score",
        )
        text_logit = self._vector(
            text_logit,
            "text logit",
        )
        image_logit = self._vector(
            image_logit,
            "image logit",
        )

        batch_sizes = {
            text_score.numel(),
            image_score.numel(),
            text_logit.numel(),
            image_logit.numel(),
        }

        if len(batch_sizes) != 1:
            raise ValueError(
                "Text and image models returned different "
                "batch sizes: "
                f"text={text_score.numel()}, "
                f"image={image_score.numel()}"
            )

        if self.fusion == "mean":
            fused_score = 0.5 * (
                text_score + image_score
            )

        elif self.fusion == "min":
            fused_score = torch.minimum(
                text_score,
                image_score,
            )

        elif self.fusion == "max":
            fused_score = torch.maximum(
                text_score,
                image_score,
            )

        else:
            if self.svm_input == "scores":
                features = torch.stack(
                    (
                        text_score,
                        image_score,
                    ),
                    dim=1,
                )
            else:
                features = torch.stack(
                    (
                        text_logit,
                        image_logit,
                    ),
                    dim=1,
                )

            fused_score = self.svm_fusion(
                features
            )

        # The late-fusion logit is defined consistently from its probability.
        eps = torch.finfo(
            fused_score.dtype
        ).eps

        fused_logit = torch.logit(
            fused_score.clamp(
                eps,
                1.0 - eps,
            )
        )

        fused_outputs = (
            fused_score.unsqueeze(1),
            fused_logit.unsqueeze(1),
        )

        if not return_components:
            return fused_outputs

        return (
            *fused_outputs,
            text_score.unsqueeze(1),
            text_logit.unsqueeze(1),
            image_score.unsqueeze(1),
            image_logit.unsqueeze(1),
        )


class LateFusionTrepatVictim:
    """TRePAT victim whose probabilities come from the fused classifier."""

    def __init__(
        self,
        model: LateFusionClassifier,
        tokenizer: Any,
        processor: Any,
        args: argparse.Namespace,
        device: torch.device,
        image: Image.Image,
    ):
        self.model = model
        self.tokenizer = tokenizer
        self.processor = processor
        self.args = args
        self.device = device
        self._prob_cache: dict[
            str,
            np.ndarray,
        ] = {}

        processed = processor(
            images=image,
            return_tensors="pt",
        ).to(device)

        pixel_values = processed[
            "pixel_values"
        ]

        if pixel_values.ndim == 4:
            pixel_values = pixel_values.unsqueeze(1)

        self.image = pixel_values

    def _build_text_input(
        self,
        texts: list[str],
    ) -> dict[
        str,
        torch.Tensor,
    ]:
        tokenized = self.tokenizer(
            texts,
            return_tensors="pt",
            padding="max_length",
            truncation=True,
            return_attention_mask=False,
            max_length=self.args.n_tokens,
        ).to(self.device)

        return {
            "input_ids": tokenized.input_ids.unsqueeze(1)
        }

    def _build_image_input(
        self,
        batch_size: int,
    ) -> dict[
        str,
        torch.Tensor,
    ]:
        image = self.image

        if (
            image.shape[0] == 1
            and batch_size > 1
        ):
            repeats = [
                batch_size
            ] + [
                1
            ] * (
                image.ndim - 1
            )
            image = image.repeat(
                *repeats
            )

        elif image.shape[0] != batch_size:
            raise ValueError(
                f"Fixed-image batch={image.shape[0]} does not "
                f"match text batch={batch_size}"
            )

        return {
            "pixel_values": image
        }

    def _scores_from_texts(
        self,
        texts: list[str],
    ) -> np.ndarray:
        text_input = self._build_text_input(
            texts
        )
        image_input = self._build_image_input(
            len(texts)
        )

        with torch.inference_mode():
            scores, _ = self.model(
                image_input,
                text_input,
            )

        return (
            scores
            .detach()
            .cpu()
            .numpy()
            .reshape(-1)
        )

    def get_prob(
        self,
        inputs: list[str],
    ) -> np.ndarray:
        missing = list(
            dict.fromkeys(
                text
                for text in inputs
                if text not in self._prob_cache
            )
        )

        if missing:
            scores = self._scores_from_texts(
                missing
            )

            for text, score in zip(
                missing,
                scores,
            ):
                self._prob_cache[text] = np.asarray(
                    [
                        1.0 - score,
                        score,
                    ],
                    dtype=np.float32,
                )

        return np.stack(
            [
                self._prob_cache[text]
                for text in inputs
            ],
            axis=0,
        )

    def get_pred(
        self,
        inputs: list[str],
    ) -> np.ndarray:
        probabilities = self.get_prob(
            inputs
        )

        return (
            probabilities[:, 1]
            > self.args.threshold
        ).astype(np.int64)


def fusion_trepat_attack(
    model: LateFusionClassifier,
    tokenizer: Any,
    processor: Any,
    args: argparse.Namespace,
    news: dict[str, Any],
    device: torch.device,
    rephraser: Rephraser,
) -> tuple[
    dict[str, Any],
    float,
]:
    """Attack text candidates using the fused probability as feedback."""
    visible_text, hidden_text = visible_text_window(
        news["txt"],
        tokenizer,
        args.n_tokens,
    )

    victim = LateFusionTrepatVictim(
        model=model,
        tokenizer=tokenizer,
        processor=processor,
        args=args,
        device=device,
        image=news["img"],
    )

    modifier = Modifier(
        rephraser,
        splitter="cascade",
        weak=False,
        max_variants=args.max_variants,
    )

    attacker = TargetedTrepatAttacker(
        modifier,
        args.source_label,
        args.target_label,
    )

    perturbed_visible = attacker.attack(
        victim,
        visible_text,
    )

    if perturbed_visible is None:
        perturbed_visible = visible_text

    perturbed_text = (
        perturbed_visible
        + hidden_text
    )

    with torch.inference_mode():
        original_embedding = model_sbert.encode(
            news["txt"],
            convert_to_tensor=True,
            device="cpu",
        )

        perturbed_embedding = model_sbert.encode(
            perturbed_text,
            convert_to_tensor=True,
            device="cpu",
        )

        similarity = util.cos_sim(
            original_embedding,
            perturbed_embedding,
        ).item()

    return (
        {
            "txt": perturbed_text,
            "img": news["img"],
        },
        similarity,
    )


def move_to_device(
    value: Any,
    device: torch.device,
) -> Any:
    """Move tensors, BatchFeatures, or nested dictionaries to one device."""
    if hasattr(value, "to"):
        return value.to(device)

    if isinstance(value, dict):
        return {
            key: move_to_device(
                item,
                device,
            )
            for key, item in value.items()
        }

    return value


def encode_text_batch(
    tokenizer: Any,
    texts: list[str],
    n_tokens: int,
    device: torch.device,
) -> dict[
    str,
    torch.Tensor,
]:
    tokenized = tokenizer(
        texts,
        return_tensors="pt",
        padding="max_length",
        truncation=True,
        return_attention_mask=False,
        max_length=n_tokens,
    ).to(device)

    return {
        "input_ids": tokenized.input_ids.unsqueeze(1)
    }


def encode_image_batch(
    processor: Any,
    images: list[Image.Image],
    device: torch.device,
) -> dict[
    str,
    torch.Tensor,
]:
    processed = processor(
        images=images,
        return_tensors="pt",
    ).to(device)

    pixel_values = processed[
        "pixel_values"
    ]

    if pixel_values.ndim == 4:
        pixel_values = pixel_values.unsqueeze(1)

    return {
        "pixel_values": pixel_values
    }


def append_outputs(
    accumulator: dict[str, list[torch.Tensor]],
    *batch_outputs: torch.Tensor,
) -> None:
    """Validate and store one batch of fused and component outputs."""
    output_names = ("scores", "logits", *COMPONENT_OUTPUT_NAMES)
    if len(batch_outputs) != len(output_names):
        raise ValueError(
            f"Expected {len(output_names)} model outputs, "
            f"received {len(batch_outputs)}"
        )

    named_outputs = dict(zip(output_names, batch_outputs))
    batch_sizes = {
        name: value.numel()
        for name, value in named_outputs.items()
    }
    if len(set(batch_sizes.values())) != 1:
        raise ValueError(f"Mismatched final output sizes: {batch_sizes}")

    for name, value in named_outputs.items():
        accumulator[name].append(
            value.detach().cpu().reshape(-1)
        )



def scenario_paths(
    output_dir: Path,
) -> dict[str, Path]:
    """Resolve every scenario through the shared path contract."""
    return {
        scope: Path(late_fusion_scenario_path(output_dir, scope))
        for scope in ("text", "image", "both")
    }


def save_parameters(
    path: Path,
    scenario: str,
    args: argparse.Namespace,
    text_parameters: dict[str, Any],
    image_parameters: dict[str, Any],
) -> None:
    """Save enough provenance to distinguish fusion-aware from post-hoc fusion."""
    scope_budgets = late_fusion_attack_budgets(scenario)
    payload = {
        "Fusion": {
            "Type": args.fusion,
            "Threshold": args.threshold,
            "SVM Model": (
                str(args.svm_model)
                if args.fusion == "svm-rbf"
                else None
            ),
            "SVM Input": (
                args.svm_input
                if args.fusion == "svm-rbf"
                else None
            ),
        },
        "Scenario": scenario,
        "Attack": {
            "Objective": "late-fusion score",
            "Independent Modalities": True,
            "Alternation": False,
            "Method": args.attack_method,
            "Source Label": args.source_label,
            "Target Label": args.target_label,
            "Only Clean-Correct Source Samples": True,
            "Budget Divisor": scope_budgets["divisor"],
            "Budgets Are Effective": True,
            "PGD Iters": (
                args.pgd_iters
                if scenario in {"image", "both"}
                else None
            ),
            "TRePAT Max Variants": (
                args.max_variants
                if scenario in {"text", "both"}
                else None
            ),
            "Epsilon": args.epsilon,
            "Alpha Factor": args.alpha_factor,
            "K (BERT Attack)": args.k,
            "Threshold Pred Score": args.threshold_pred_score,
            "Max Words to Attack": args.max_words_to_attack,
            "Max Candidates per Word": (
                args.max_candidates_per_word
            ),
            "Max Words for Importance": (
                args.max_words_for_importance
            ),
            "Minimum Text Similarity": (
                args.min_txt_similarity
            ),
        },
        "Text Model Parameters": text_parameters,
        "Image Model Parameters": image_parameters,
    }

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    with path.open(
        "w",
        encoding="utf-8",
    ) as handle:
        json.dump(
            payload,
            handle,
            indent=4,
        )
        handle.write("\n")


def main() -> None:
    args, text_parameters, image_parameters = parse_args()

    validate_args(
        args,
        text_parameters,
        image_parameters,
    )

    device = torch.device(DEVICE)
    device_mlm = torch.device(DEVICE_MLM)

    text_model_args = model_args_from_parameters(
        text_parameters,
        "text",
        args.text_model_path,
    )

    image_model_args = model_args_from_parameters(
        image_parameters,
        "image",
        args.image_model_path,
    )

    text_model, tokenizer, _ = load_model(
        device,
        text_model_args,
        str(args.text_model_path),
    )

    image_model, _, processor = load_model(
        device,
        image_model_args,
        str(args.image_model_path),
    )

    svm_fusion = None

    if args.fusion == "svm-rbf":
        fitted_svm = joblib.load(
            args.svm_model
        )

        svm_fusion = DifferentiableRBFSVMFusion(
            fitted_svm
        ).to(device)

    model = LateFusionClassifier(
        text_model=text_model,
        image_model=image_model,
        fusion=args.fusion,
        svm_fusion=svm_fusion,
        svm_input=args.svm_input,
    ).to(device)

    model.eval()

    # Existing BERTAttack helpers pass the fixed image only for multimodal
    # modalities. The actual two underlying models were already loaded above.
    args.modality = "feature-fusion"

    rephraser = None
    bertattack_tokenizer = None
    bertattack_mlm = None

    if args.attack_scope in {
        "text",
        "both",
    }:
        if args.attack_method == "trepat":
            rephraser = Rephraser(
                model=ATTACK_MODEL,
                device=device_mlm,
                command=COMMAND,
            )
        else:
            bertattack_tokenizer = (
                AutoTokenizer.from_pretrained(
                    "bert-base-uncased",
                    use_fast=True,
                )
            )

            bertattack_mlm = (
                AutoModelForMaskedLM.from_pretrained(
                    "bert-base-uncased"
                ).to(device_mlm)
            )

            bertattack_mlm.eval()

    dataset_classes, load_functions = (
        load_available_datasets()
    )

    if args.dataset not in dataset_classes:
        raise ValueError(
            f"Unknown dataset {args.dataset!r}; "
            f"available: {sorted(dataset_classes)}"
        )

    if args.test_data is None:
        candidates = sorted(
            glob.glob(
                f"data_loading/{args.dataset}/test.*"
            )
        )

        if not candidates:
            raise FileNotFoundError(
                f"No data_loading/{args.dataset}/test.* "
                "file was found"
            )

        test_data = Path(
            candidates[0]
        )

    else:
        test_data = args.test_data

    if not test_data.is_file():
        raise FileNotFoundError(
            f"Test annotations do not exist: "
            f"{test_data}"
        )

    images_dir = (
        args.images_dir
        if args.images_dir is not None
        else Path(
            f"data_loading/{args.dataset}/images"
        )
    )

    if not images_dir.is_dir():
        raise FileNotFoundError(
            f"Image directory does not exist: "
            f"{images_dir}"
        )

    dataset_test = my_datasets.get_dataset(
        dataset_classes[args.dataset],
        load_functions[args.dataset],
        args.n_tokens,
        processor,
        tokenizer,
        str(test_data),
        str(images_dir),
    )

    sampler = None

    if args.subset_size is not None:
        sampler = list(
            range(
                min(
                    args.subset_size,
                    len(dataset_test),
                )
            )
        )

    dataloader_test = DataLoader(
        dataset_test,
        batch_size=args.batch_size,
        shuffle=False,
        sampler=sampler,
        num_workers=args.num_workers,
    )

    output_dir = (
        args.output_dir
        if args.output_dir is not None
        else (
            args.results_path
            / "perturbed"
            / "late-fusion"
            / args.fusion
        )
    )

    dump_dir = (
        args.dump_dir
        if args.dump_dir is not None
        else (
            Path(LATE_FUSION_DATA_DIR)
            / args.fusion
            / args.attack_scope
        )
    )

    # Each launcher invocation owns exactly one output scenario, so separate
    # runs cannot overwrite another scenario's artifact.
    requested_scenarios = {
        args.attack_scope
    }

    active_budgets = []

    if args.attack_scope in {
        "text",
        "both",
    }:
        active_budgets.append(
            f"TRePAT max variants={args.max_variants}"
        )

    if args.attack_scope in {
        "image",
        "both",
    }:
        active_budgets.append(
            f"PGD iterations={args.pgd_iters}"
        )

    print(
        "Effective attack budget: "
        f"{', '.join(active_budgets)}"
    )

    output_names = ("scores", "logits", *COMPONENT_OUTPUT_NAMES)
    outputs = {
        scenario: {
            name: []
            for name in output_names
        }
        for scenario in requested_scenarios
    }

    labels_list: list[
        torch.Tensor
    ] = []

    indices_list: list[
        torch.Tensor
    ] = []

    similarities: list[
        float
    ] = []

    ssims: list[
        float
    ] = []

    perturbed_text_rows: list[
        dict[str, Any]
    ] = []

    attacked_samples = 0

    for (
        images,
        labels,
        texts,
        _,
        indices,
    ) in tqdm(
        dataloader_test,
        desc=(
            f"Fusion-aware "
            f"{args.fusion} attack"
        ),
        total=len(dataloader_test),
    ):
        images_device = move_to_device(
            images,
            device,
        )

        texts_device = move_to_device(
            texts,
            device,
        )

        with torch.inference_mode():
            clean_scores, _ = model(
                images_device,
                texts_device,
            )

        clean_predictions = (
            clean_scores
            .detach()
            .cpu()
            .reshape(-1)
            > args.threshold
        ).to(torch.int64)

        perturbed_texts: list[
            str
        ] = []

        perturbed_images: list[
            Image.Image
        ] = []

        for position, label in tqdm(
            enumerate(labels.tolist()),
            desc="Attacking batch samples",
            total=len(labels),
            leave=False,
        ):
            index = int(
                indices[position].item()
            )

            clean_news = {
                "txt": dataset_test.texts[
                    index
                ],
                "img": Image.open(
                    os.path.join(
                        dataset_test.img_dir,
                        dataset_test.imgs_path[index],
                    )
                ).convert("RGB"),
            }

            perturbed_text = clean_news[
                "txt"
            ]
            perturbed_image = clean_news[
                "img"
            ]
            text_similarity = 1.0
            image_ssim = 1.0

            clean_is_source = (
                int(
                    clean_predictions[
                        position
                    ].item()
                )
                == args.source_label
            )

            should_attack = (
                label == args.source_label
                and clean_is_source
            )

            if should_attack:
                attacked_samples += 1

                # Both calls deliberately receive clean_news. Therefore neither
                # modality attack observes the perturbation produced for the
                # other.
                if args.attack_scope in {
                    "text",
                    "both",
                }:
                    if args.attack_method == "trepat":
                        (
                            text_news,
                            text_similarity,
                        ) = fusion_trepat_attack(
                            model,
                            tokenizer,
                            processor,
                            args,
                            clean_news,
                            device,
                            rephraser,
                        )

                    else:
                        with torch.no_grad():
                            (
                                text_news,
                                text_similarity,
                            ) = bertattack_attack(
                                model,
                                tokenizer,
                                processor,
                                args,
                                clean_news,
                                label,
                                device,
                                bertattack_tokenizer,
                                bertattack_mlm,
                                device_mlm,
                            )

                    if (
                        text_similarity
                        >= args.min_txt_similarity
                    ):
                        perturbed_text = text_news[
                            "txt"
                        ]
                    else:
                        text_similarity = 1.0

                    perturbed_text_rows.append(
                        {
                            "index": index,
                            "original": clean_news["txt"],
                            "perturbed": perturbed_text,
                        }
                    )

                if args.attack_scope in {
                    "image",
                    "both",
                }:
                    (
                        image_news,
                        image_ssim,
                        _,
                    ) = img_perturbation(
                        model,
                        tokenizer,
                        processor,
                        args,
                        clean_news,
                        torch.tensor(
                            [label],
                            device=device,
                        ),
                    )

                    perturbed_image = image_news[
                        "img"
                    ]

                    image_ssim = float(
                        image_ssim.item()
                        if hasattr(
                            image_ssim,
                            "item",
                        )
                        else image_ssim
                    )

                    save_perturbed_image(
                        str(
                            dump_dir
                            / "images"
                        ),
                        index,
                        perturbed_image,
                    )

                if torch.cuda.is_available():
                    torch.cuda.empty_cache()

            perturbed_texts.append(
                perturbed_text
            )
            perturbed_images.append(
                perturbed_image
            )
            similarities.append(
                float(text_similarity)
            )
            ssims.append(
                float(image_ssim)
            )

        encoded_texts = None
        encoded_images = None

        if args.attack_scope in {
            "text",
            "both",
        }:
            encoded_texts = encode_text_batch(
                tokenizer,
                perturbed_texts,
                args.n_tokens,
                device,
            )

        if args.attack_scope in {
            "image",
            "both",
        }:
            encoded_images = encode_image_batch(
                processor,
                perturbed_images,
                device,
            )

        scenario_inputs = {
            "text": (images_device, encoded_texts),
            "image": (encoded_images, texts_device),
            "both": (encoded_images, encoded_texts),
        }

        with torch.inference_mode():
            for scenario in sorted(requested_scenarios):
                scenario_outputs = model(
                    *scenario_inputs[scenario],
                    return_components=True,
                )
                append_outputs(
                    outputs[scenario],
                    *scenario_outputs,
                )

        labels_list.append(
            torch.as_tensor(
                labels
            )
            .detach()
            .cpu()
            .reshape(-1)
        )

        indices_list.append(
            torch.as_tensor(
                indices
            )
            .detach()
            .cpu()
            .reshape(-1)
        )

    if not labels_list:
        raise ValueError(
            "The test dataloader produced no samples"
        )

    y_true = torch.cat(
        labels_list
    ).numpy()

    sample_indices = torch.cat(
        indices_list
    ).numpy()

    paths = scenario_paths(
        output_dir
    )

    for scenario in sorted(
        requested_scenarios
    ):
        scores = (
            torch.cat(
                outputs[scenario]["scores"]
            )
            .numpy()
            .reshape(-1)
        )

        logits = (
            torch.cat(
                outputs[scenario]["logits"]
            )
            .numpy()
            .reshape(-1)
        )

        component_outputs = {
            column: torch.cat(outputs[scenario][name]).numpy().reshape(-1)
            for column, name in zip(
                COMPONENT_OUTPUT_COLUMNS,
                COMPONENT_OUTPUT_NAMES,
            )
        }

        predictions = (
            scores > args.threshold
        ).astype(np.int64)

        result_path = paths[
            scenario
        ]

        result_path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        save_predictions(
            y_true,
            predictions,
            scores,
            logits,
            sample_indices,
            str(result_path),
            ssims=(
                np.asarray(ssims)
                if scenario in {
                    "image",
                    "both",
                }
                else None
            ),
            txt_similarities=(
                np.asarray(similarities)
                if scenario in {
                    "text",
                    "both",
                }
                else None
            ),
            extra_columns=component_outputs,
        )

        save_parameters(
            result_path.parent
            / "parameters.json",
            scenario,
            args,
            text_parameters,
            image_parameters,
        )

        print(
            f"Saved {result_path}"
        )

    if perturbed_text_rows:
        save_perturbed_texts(
            str(dump_dir),
            perturbed_text_rows,
        )

    print(
        f"Attacked {attacked_samples} source-class samples "
        f"using the {args.fusion} fused score."
    )


if __name__ == "__main__":
    main()